name: Daily Repository Update

on:

  push:
    branches:
      - main
      
  schedule:
  - cron: "0 7,9,11 * * 0,1,3,5"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "iburhanwebb@gmail.com"
          git config --local user.name "zwayth"
          git add -A
          
          arr[0]="commit"
          arr[1]="commit"
          arr[2]="commit"
          arr[3]="commit"
          arr[4]="commit"
          arr[5]="commit"
          arr[6]="commit"
          arr[7]="commit"
          arr[8]="commit"
          arr[9]="commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
